// Compiled shader for Windows, Mac, Linux

//////////////////////////////////////////////////////////////////////////
// 
// NOTE: This is *not* a valid shader file, the contents are provided just
// for information and for debugging purposes only.
// 
//////////////////////////////////////////////////////////////////////////
// Skipping shader variants that would not be included into build of current scene.

Shader "Hovl/Particles/Scroll" {
Properties {
 _MainTex ("MainTex", 2D) = "white" { }
 _Noise ("Noise", 2D) = "white" { }
 _Flow ("Flow", 2D) = "white" { }
 _Mask ("Mask", 2D) = "white" { }
 _SpeedMainTexUVNoiseZW ("Speed MainTex U/V + Noise Z/W", Vector) = (0.000000,0.000000,0.000000,0.000000)
 _DistortionSpeedXYPowerZ ("Distortion Speed XY Power Z", Vector) = (0.000000,0.000000,0.000000,0.000000)
 _Emission ("Emission", Float) = 2.000000
 _Color ("Color", Color) = (0.500000,0.500000,0.500000,1.000000)
 _Opacity ("Opacity", Range(0.000000,1.000000)) = 1.000000
 _PathSet0ifyouuseinPS ("Path(Set 0 if you use in PS)", Range(0.000000,1.000000)) = 0.000000
 _Noisedistortpower ("Noise distort power", Float) = 1.000000
[Toggle]  _UsePScustomdataW ("Use PS custom data W", Float) = 1.000000
[MaterialToggle]  _Usedepth ("Use depth?", Float) = 0.000000
 _InvFade ("Soft Particles Factor", Range(0.010000,3.000000)) = 1.000000
[HideInInspector]  _texcoord ("", 2D) = "white" { }
}
SubShader { 
 Tags { "QUEUE"="Transparent" "IGNOREPROJECTOR"="true" "RenderType"="Transparent" "PreviewType"="Plane" }


 // Stats for Vertex shader:
 //        d3d11: 16 avg math (8..24)
 // Stats for Fragment shader:
 //        d3d11: 41 avg math (37..46), 4 avg texture (4..5)
 Pass {
  Tags { "QUEUE"="Transparent" "IGNOREPROJECTOR"="true" "RenderType"="Transparent" "PreviewType"="Plane" }
  ZWrite Off
  Cull Off
  Blend SrcAlpha OneMinusSrcAlpha
  ColorMask RGB
  //////////////////////////////////
  //                              //
  //      Compiled programs       //
  //                              //
  //////////////////////////////////
//////////////////////////////////////////////////////
Keywords: <none>
-- Hardware tier variant: Tier 1
-- Vertex shader for "d3d11":
// Stats: 8 math, 2 temp registers
Uses vertex data channel "Vertex"
Uses vertex data channel "Color"
Uses vertex data channel "TexCoord0"

Constant Buffer "UnityPerDraw" (176 bytes) on slot 0 {
  Matrix4x4 unity_ObjectToWorld at 0
}
Constant Buffer "UnityPerFrame" (368 bytes) on slot 1 {
  Matrix4x4 unity_MatrixVP at 272
}

Shader Disassembly:
//
// Generated by Microsoft (R) D3D Shader Disassembler
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// POSITION                 0   xyzw        0     NONE   float   xyz 
// COLOR                    0   xyzw        1     NONE   float   xyzw
// TEXCOORD                 0   xyzw        2     NONE   float   xyzw
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_POSITION              0   xyzw        0      POS   float   xyzw
// COLOR                    0   xyzw        1     NONE   float   xyzw
// TEXCOORD                 0   xyzw        2     NONE   float   xyzw
//
      vs_4_0
      dcl_constantbuffer CB0[4], immediateIndexed
      dcl_constantbuffer CB1[21], immediateIndexed
      dcl_input v0.xyz
      dcl_input v1.xyzw
      dcl_input v2.xyzw
      dcl_output_siv o0.xyzw, position
      dcl_output o1.xyzw
      dcl_output o2.xyzw
      dcl_temps 2
   0: mul r0.xyzw, v0.yyyy, cb0[1].xyzw
   1: mad r0.xyzw, cb0[0].xyzw, v0.xxxx, r0.xyzw
   2: mad r0.xyzw, cb0[2].xyzw, v0.zzzz, r0.xyzw
   3: add r0.xyzw, r0.xyzw, cb0[3].xyzw
   4: mul r1.xyzw, r0.yyyy, cb1[18].xyzw
   5: mad r1.xyzw, cb1[17].xyzw, r0.xxxx, r1.xyzw
   6: mad r1.xyzw, cb1[19].xyzw, r0.zzzz, r1.xyzw
   7: mad o0.xyzw, cb1[20].xyzw, r0.wwww, r1.xyzw
   8: mov o1.xyzw, v1.xyzw
   9: mov o2.xyzw, v2.xyzw
  10: ret 
// Approximately 0 instruction slots used


-- Hardware tier variant: Tier 1
-- Fragment shader for "d3d11":
// Stats: 37 math, 2 temp registers, 4 textures
Set 2D Texture "_Flow" to slot 0 sampler slot 1
Set 2D Texture "_Noise" to slot 1 sampler slot 2
Set 2D Texture "_MainTex" to slot 2 sampler slot 0
Set 2D Texture "_Mask" to slot 3

Constant Buffer "$Globals" (224 bytes) on slot 0 {
  Vector4 _MainTex_ST at 48
  Vector4 _SpeedMainTexUVNoiseZW at 80
  Vector4 _DistortionSpeedXYPowerZ at 96
  Vector4 _Flow_ST at 112
  Vector4 _Noise_ST at 128
  Float _PathSet0ifyouuseinPS at 144
  Vector4 _Color at 160
  Float _Emission at 176
  Float _Noisedistortpower at 180
  Float _UsePScustomdataW at 184
  Float _Opacity at 188
  Vector4 _Mask_ST at 192
}
Constant Buffer "UnityPerCamera" (144 bytes) on slot 1 {
  Vector4 _Time at 0
}

Shader Disassembly:
//
// Generated by Microsoft (R) D3D Shader Disassembler
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_POSITION              0   xyzw        0      POS   float       
// COLOR                    0   xyzw        1     NONE   float   xyzw
// TEXCOORD                 0   xyzw        2     NONE   float   xyzw
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Target                0   xyzw        0   TARGET   float   xyzw
//
      ps_4_0
      dcl_constantbuffer CB0[13], immediateIndexed
      dcl_constantbuffer CB1[1], immediateIndexed
      dcl_sampler s0, mode_default
      dcl_sampler s1, mode_default
      dcl_sampler s2, mode_default
      dcl_sampler s3, mode_default
      dcl_resource_texture2d (float,float,float,float) t0
      dcl_resource_texture2d (float,float,float,float) t1
      dcl_resource_texture2d (float,float,float,float) t2
      dcl_resource_texture2d (float,float,float,float) t3
      dcl_input_ps linear v1.xyzw
      dcl_input_ps linear v2.xyzw
      dcl_output o0.xyzw
      dcl_temps 2
   0: mad r0.xy, v2.xyxx, cb0[8].xyxx, cb0[8].zwzz
   1: mad r0.xy, cb1[0].yyyy, cb0[5].zwzz, r0.xyxx
   2: add r0.w, v2.z, cb0[9].x
   3: add r0.y, -r0.w, r0.y
   4: add r0.w, -r0.w, l(1.000000)
   5: div r0.z, r0.y, r0.w
   6: mad r0.yw, v2.xxxy, cb0[7].xxxy, cb0[7].zzzw
   7: mad r0.yw, cb1[0].yyyy, cb0[6].xxxy, r0.yyyw
   8: sample r1.xyzw, r0.ywyy, t0.xyzw, s1
   9: mad r0.xy, -r1.xyxx, cb0[6].zzzz, r0.xzxx
  10: sample r0.xyzw, r0.xyxx, t1.xyzw, s2
  11: add_sat r0.xyzw, r0.xyzw, l(-0.100000, -0.100000, -0.100000, -0.100000)
  12: mad r1.zw, v2.xxxy, cb0[3].xxxy, cb0[3].zzzw
  13: mad r1.zw, cb1[0].yyyy, cb0[5].xxxy, r1.zzzw
  14: mad r1.xy, -r1.xyxx, cb0[6].zzzz, r1.zwzz
  15: sample r1.xyzw, r1.xyxx, t2.xyzw, s0
  16: mul r0.xyz, r0.xyzx, r1.xyzx
  17: log r0.w, r0.w
  18: mul r0.xyz, r0.xyzx, cb0[10].xyzx
  19: mul r0.xyz, r0.xyzx, v1.xyzx
  20: add r1.x, -v2.y, l(1.000000)
  21: log r1.x, r1.x
  22: mul r1.x, r1.x, l(40.000000)
  23: exp r1.x, r1.x
  24: add r1.x, -r1.x, l(1.000000)
  25: max r1.x, r1.x, l(0.000000)
  26: mul r0.xyz, r0.xyzx, r1.xxxx
  27: mul o0.xyz, r0.xyzx, cb0[11].xxxx
  28: mov_sat r0.x, v2.w
  29: mul r0.x, r0.x, cb0[11].z
  30: mad r0.x, r0.x, l(10.000000), cb0[11].y
  31: mul r0.x, r0.w, r0.x
  32: exp r0.x, r0.x
  33: min r0.x, r0.x, l(1.000000)
  34: mad_sat r0.x, r0.x, l(7.000000), l(-2.000000)
  35: mul r0.x, r1.x, r0.x
  36: mul r0.x, r0.x, cb0[10].w
  37: mul r0.x, r0.x, v1.w
  38: mul r0.x, r0.x, cb0[11].w
  39: mad r0.yz, v2.xxyx, cb0[12].xxyx, cb0[12].zzwz
  40: sample r1.xyzw, r0.yzyy, t3.xyzw, s3
  41: mul o0.w, r0.x, r1.w
  42: ret 
// Approximately 0 instruction slots used


//////////////////////////////////////////////////////
Keywords: FOG_EXP2
-- Hardware tier variant: Tier 1
-- Vertex shader for "d3d11":
// Stats: 15 math, 2 temp registers
Uses vertex data channel "Vertex"
Uses vertex data channel "Color"
Uses vertex data channel "TexCoord0"

Constant Buffer "UnityPerCamera" (144 bytes) on slot 0 {
  Vector4 _ProjectionParams at 80
}
Constant Buffer "UnityPerDraw" (176 bytes) on slot 1 {
  Matrix4x4 unity_ObjectToWorld at 0
}
Constant Buffer "UnityPerFrame" (368 bytes) on slot 2 {
  Matrix4x4 unity_MatrixVP at 272
}
Constant Buffer "UnityFog" (32 bytes) on slot 3 {
  Vector4 unity_FogParams at 16
}

Shader Disassembly:
//
// Generated by Microsoft (R) D3D Shader Disassembler
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// POSITION                 0   xyzw        0     NONE   float   xyz 
// COLOR                    0   xyzw        1     NONE   float   xyzw
// TEXCOORD                 0   xyzw        2     NONE   float   xyzw
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_POSITION              0   xyzw        0      POS   float   xyzw
// COLOR                    0   xyzw        1     NONE   float   xyzw
// TEXCOORD                 0   xyzw        2     NONE   float   xyzw
// TEXCOORD                 1   x           3     NONE   float   x   
//
      vs_4_0
      dcl_constantbuffer CB0[6], immediateIndexed
      dcl_constantbuffer CB1[4], immediateIndexed
      dcl_constantbuffer CB2[21], immediateIndexed
      dcl_constantbuffer CB3[2], immediateIndexed
      dcl_input v0.xyz
      dcl_input v1.xyzw
      dcl_input v2.xyzw
      dcl_output_siv o0.xyzw, position
      dcl_output o1.xyzw
      dcl_output o2.xyzw
      dcl_output o3.x
      dcl_temps 2
   0: mul r0.xyzw, v0.yyyy, cb1[1].xyzw
   1: mad r0.xyzw, cb1[0].xyzw, v0.xxxx, r0.xyzw
   2: mad r0.xyzw, cb1[2].xyzw, v0.zzzz, r0.xyzw
   3: add r0.xyzw, r0.xyzw, cb1[3].xyzw
   4: mul r1.xyzw, r0.yyyy, cb2[18].xyzw
   5: mad r1.xyzw, cb2[17].xyzw, r0.xxxx, r1.xyzw
   6: mad r1.xyzw, cb2[19].xyzw, r0.zzzz, r1.xyzw
   7: mad r0.xyzw, cb2[20].xyzw, r0.wwww, r1.xyzw
   8: mov o0.xyzw, r0.xyzw
   9: div r0.x, r0.z, cb0[5].y
  10: add r0.x, -r0.x, l(1.000000)
  11: mul r0.x, r0.x, cb0[5].z
  12: max r0.x, r0.x, l(0.000000)
  13: mul r0.x, r0.x, cb3[1].x
  14: mul r0.x, r0.x, -r0.x
  15: exp o3.x, r0.x
  16: mov o1.xyzw, v1.xyzw
  17: mov o2.xyzw, v2.xyzw
  18: ret 
// Approximately 0 instruction slots used


-- Hardware tier variant: Tier 1
-- Fragment shader for "d3d11":
// Stats: 38 math, 2 temp registers, 4 textures
Set 2D Texture "_Flow" to slot 0 sampler slot 1
Set 2D Texture "_Noise" to slot 1 sampler slot 2
Set 2D Texture "_MainTex" to slot 2 sampler slot 0
Set 2D Texture "_Mask" to slot 3

Constant Buffer "$Globals" (224 bytes) on slot 0 {
  Vector4 _MainTex_ST at 48
  Vector4 _SpeedMainTexUVNoiseZW at 80
  Vector4 _DistortionSpeedXYPowerZ at 96
  Vector4 _Flow_ST at 112
  Vector4 _Noise_ST at 128
  Float _PathSet0ifyouuseinPS at 144
  Vector4 _Color at 160
  Float _Emission at 176
  Float _Noisedistortpower at 180
  Float _UsePScustomdataW at 184
  Float _Opacity at 188
  Vector4 _Mask_ST at 192
}
Constant Buffer "UnityPerCamera" (144 bytes) on slot 1 {
  Vector4 _Time at 0
}
Constant Buffer "UnityFog" (32 bytes) on slot 2 {
  Vector4 unity_FogColor at 0
}

Shader Disassembly:
//
// Generated by Microsoft (R) D3D Shader Disassembler
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_POSITION              0   xyzw        0      POS   float       
// COLOR                    0   xyzw        1     NONE   float   xyzw
// TEXCOORD                 0   xyzw        2     NONE   float   xyzw
// TEXCOORD                 1   x           3     NONE   float   x   
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Target                0   xyzw        0   TARGET   float   xyzw
//
      ps_4_0
      dcl_constantbuffer CB0[13], immediateIndexed
      dcl_constantbuffer CB1[1], immediateIndexed
      dcl_constantbuffer CB2[1], immediateIndexed
      dcl_sampler s0, mode_default
      dcl_sampler s1, mode_default
      dcl_sampler s2, mode_default
      dcl_sampler s3, mode_default
      dcl_resource_texture2d (float,float,float,float) t0
      dcl_resource_texture2d (float,float,float,float) t1
      dcl_resource_texture2d (float,float,float,float) t2
      dcl_resource_texture2d (float,float,float,float) t3
      dcl_input_ps linear v1.xyzw
      dcl_input_ps linear v2.xyzw
      dcl_input_ps linear v3.x
      dcl_output o0.xyzw
      dcl_temps 2
   0: mad r0.xy, v2.xyxx, cb0[8].xyxx, cb0[8].zwzz
   1: mad r0.xy, cb1[0].yyyy, cb0[5].zwzz, r0.xyxx
   2: add r0.w, v2.z, cb0[9].x
   3: add r0.y, -r0.w, r0.y
   4: add r0.w, -r0.w, l(1.000000)
   5: div r0.z, r0.y, r0.w
   6: mad r0.yw, v2.xxxy, cb0[7].xxxy, cb0[7].zzzw
   7: mad r0.yw, cb1[0].yyyy, cb0[6].xxxy, r0.yyyw
   8: sample r1.xyzw, r0.ywyy, t0.xyzw, s1
   9: mad r0.xy, -r1.xyxx, cb0[6].zzzz, r0.xzxx
  10: sample r0.xyzw, r0.xyxx, t1.xyzw, s2
  11: add_sat r0.xyzw, r0.xyzw, l(-0.100000, -0.100000, -0.100000, -0.100000)
  12: mad r1.zw, v2.xxxy, cb0[3].xxxy, cb0[3].zzzw
  13: mad r1.zw, cb1[0].yyyy, cb0[5].xxxy, r1.zzzw
  14: mad r1.xy, -r1.xyxx, cb0[6].zzzz, r1.zwzz
  15: sample r1.xyzw, r1.xyxx, t2.xyzw, s0
  16: mul r0.xyz, r0.xyzx, r1.xyzx
  17: log r0.w, r0.w
  18: mul r0.xyz, r0.xyzx, cb0[10].xyzx
  19: mul r0.xyz, r0.xyzx, v1.xyzx
  20: add r1.x, -v2.y, l(1.000000)
  21: log r1.x, r1.x
  22: mul r1.x, r1.x, l(40.000000)
  23: exp r1.x, r1.x
  24: add r1.x, -r1.x, l(1.000000)
  25: max r1.x, r1.x, l(0.000000)
  26: mul r0.xyz, r0.xyzx, r1.xxxx
  27: mad r0.xyz, r0.xyzx, cb0[11].xxxx, -cb2[0].xyzx
  28: mov_sat r1.y, v3.x
  29: mad o0.xyz, r1.yyyy, r0.xyzx, cb2[0].xyzx
  30: mov_sat r0.x, v2.w
  31: mul r0.x, r0.x, cb0[11].z
  32: mad r0.x, r0.x, l(10.000000), cb0[11].y
  33: mul r0.x, r0.w, r0.x
  34: exp r0.x, r0.x
  35: min r0.x, r0.x, l(1.000000)
  36: mad_sat r0.x, r0.x, l(7.000000), l(-2.000000)
  37: mul r0.x, r1.x, r0.x
  38: mul r0.x, r0.x, cb0[10].w
  39: mul r0.x, r0.x, v1.w
  40: mul r0.x, r0.x, cb0[11].w
  41: mad r0.yz, v2.xxyx, cb0[12].xxyx, cb0[12].zzwz
  42: sample r1.xyzw, r0.yzyy, t3.xyzw, s3
  43: mul o0.w, r0.x, r1.w
  44: ret 
// Approximately 0 instruction slots used


//////////////////////////////////////////////////////
Keywords: SOFTPARTICLES_ON
-- Hardware tier variant: Tier 1
-- Vertex shader for "d3d11":
// Stats: 17 math, 2 temp registers
Uses vertex data channel "Vertex"
Uses vertex data channel "Color"
Uses vertex data channel "TexCoord0"

Constant Buffer "UnityPerCamera" (144 bytes) on slot 0 {
  Vector4 _ProjectionParams at 80
}
Constant Buffer "UnityPerDraw" (176 bytes) on slot 1 {
  Matrix4x4 unity_ObjectToWorld at 0
}
Constant Buffer "UnityPerFrame" (368 bytes) on slot 2 {
  Matrix4x4 unity_MatrixV at 144
  Matrix4x4 unity_MatrixVP at 272
}

Shader Disassembly:
//
// Generated by Microsoft (R) D3D Shader Disassembler
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// POSITION                 0   xyzw        0     NONE   float   xyz 
// COLOR                    0   xyzw        1     NONE   float   xyzw
// TEXCOORD                 0   xyzw        2     NONE   float   xyzw
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_POSITION              0   xyzw        0      POS   float   xyzw
// COLOR                    0   xyzw        1     NONE   float   xyzw
// TEXCOORD                 0   xyzw        2     NONE   float   xyzw
// TEXCOORD                 2   xyzw        3     NONE   float   xyzw
//
      vs_4_0
      dcl_constantbuffer CB0[6], immediateIndexed
      dcl_constantbuffer CB1[4], immediateIndexed
      dcl_constantbuffer CB2[21], immediateIndexed
      dcl_input v0.xyz
      dcl_input v1.xyzw
      dcl_input v2.xyzw
      dcl_output_siv o0.xyzw, position
      dcl_output o1.xyzw
      dcl_output o2.xyzw
      dcl_output o3.xyzw
      dcl_temps 2
   0: mul r0.xyzw, v0.yyyy, cb1[1].xyzw
   1: mad r0.xyzw, cb1[0].xyzw, v0.xxxx, r0.xyzw
   2: mad r0.xyzw, cb1[2].xyzw, v0.zzzz, r0.xyzw
   3: add r0.xyzw, r0.xyzw, cb1[3].xyzw
   4: mul r1.xyzw, r0.yyyy, cb2[18].xyzw
   5: mad r1.xyzw, cb2[17].xyzw, r0.xxxx, r1.xyzw
   6: mad r1.xyzw, cb2[19].xyzw, r0.zzzz, r1.xyzw
   7: mad r1.xyzw, cb2[20].xyzw, r0.wwww, r1.xyzw
   8: mov o0.xyzw, r1.xyzw
   9: mov o1.xyzw, v1.xyzw
  10: mov o2.xyzw, v2.xyzw
  11: mul r0.y, r0.y, cb2[10].z
  12: mad r0.x, cb2[9].z, r0.x, r0.y
  13: mad r0.x, cb2[11].z, r0.z, r0.x
  14: mad r0.x, cb2[12].z, r0.w, r0.x
  15: mov o3.z, -r0.x
  16: mul r0.x, r1.y, cb0[5].x
  17: mul r0.w, r0.x, l(0.500000)
  18: mul r0.xz, r1.xxwx, l(0.500000, 0.000000, 0.500000, 0.000000)
  19: mov o3.w, r1.w
  20: add o3.xy, r0.zzzz, r0.xwxx
  21: ret 
// Approximately 0 instruction slots used


-- Hardware tier variant: Tier 1
-- Fragment shader for "d3d11":
// Stats: 45 math, 4 temp registers, 5 textures
Set 2D Texture "_CameraDepthTexture" to slot 0
Set 2D Texture "_Flow" to slot 1 sampler slot 2
Set 2D Texture "_Noise" to slot 2 sampler slot 3
Set 2D Texture "_MainTex" to slot 3 sampler slot 1
Set 2D Texture "_Mask" to slot 4

Constant Buffer "$Globals" (224 bytes) on slot 0 {
  Vector4 _MainTex_ST at 48
  Float _InvFade at 64
  Vector4 _SpeedMainTexUVNoiseZW at 80
  Vector4 _DistortionSpeedXYPowerZ at 96
  Vector4 _Flow_ST at 112
  Vector4 _Noise_ST at 128
  Float _PathSet0ifyouuseinPS at 144
  Vector4 _Color at 160
  Float _Emission at 176
  Float _Noisedistortpower at 180
  Float _UsePScustomdataW at 184
  Float _Opacity at 188
  Vector4 _Mask_ST at 192
  Float _Usedepth at 208
}
Constant Buffer "UnityPerCamera" (144 bytes) on slot 1 {
  Vector4 _Time at 0
  Vector4 _ZBufferParams at 112
}

Shader Disassembly:
//
// Generated by Microsoft (R) D3D Shader Disassembler
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_POSITION              0   xyzw        0      POS   float       
// COLOR                    0   xyzw        1     NONE   float   xyzw
// TEXCOORD                 0   xyzw        2     NONE   float   xyzw
// TEXCOORD                 2   xyzw        3     NONE   float   xyzw
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Target                0   xyzw        0   TARGET   float   xyzw
//
      ps_4_0
      dcl_constantbuffer CB0[14], immediateIndexed
      dcl_constantbuffer CB1[8], immediateIndexed
      dcl_sampler s0, mode_default
      dcl_sampler s1, mode_default
      dcl_sampler s2, mode_default
      dcl_sampler s3, mode_default
      dcl_sampler s4, mode_default
      dcl_resource_texture2d (float,float,float,float) t0
      dcl_resource_texture2d (float,float,float,float) t1
      dcl_resource_texture2d (float,float,float,float) t2
      dcl_resource_texture2d (float,float,float,float) t3
      dcl_resource_texture2d (float,float,float,float) t4
      dcl_input_ps linear v1.xyzw
      dcl_input_ps linear v2.xyzw
      dcl_input_ps linear v3.xyzw
      dcl_output o0.xyzw
      dcl_temps 4
   0: div r0.xy, v3.xyxx, v3.wwww
   1: sample r0.xyzw, r0.xyxx, t0.xyzw, s0
   2: mad r0.x, cb1[7].z, r0.x, cb1[7].w
   3: div r0.x, l(1.000000, 1.000000, 1.000000, 1.000000), r0.x
   4: add r0.x, r0.x, -v3.z
   5: mul_sat r0.x, r0.x, cb0[4].x
   6: add r0.x, r0.x, l(-1.000000)
   7: mad r0.x, cb0[13].x, r0.x, l(1.000000)
   8: mul r0.x, r0.x, v1.w
   9: mad r0.yz, v2.xxyx, cb0[8].xxyx, cb0[8].zzwz
  10: mad r1.xy, cb1[0].yyyy, cb0[5].zwzz, r0.yzyy
  11: add r0.y, v2.z, cb0[9].x
  12: add r0.z, -r0.y, r1.y
  13: add r0.y, -r0.y, l(1.000000)
  14: div r1.z, r0.z, r0.y
  15: mad r0.yz, v2.xxyx, cb0[7].xxyx, cb0[7].zzwz
  16: mad r0.yz, cb1[0].yyyy, cb0[6].xxyx, r0.yyzy
  17: sample r2.xyzw, r0.yzyy, t1.xyzw, s2
  18: mad r0.yz, -r2.xxyx, cb0[6].zzzz, r1.xxzx
  19: sample r1.xyzw, r0.yzyy, t2.xyzw, s3
  20: add_sat r1.xyzw, r1.xyzw, l(-0.100000, -0.100000, -0.100000, -0.100000)
  21: log r0.y, r1.w
  22: mov_sat r0.z, v2.w
  23: mul r0.z, r0.z, cb0[11].z
  24: mad r0.z, r0.z, l(10.000000), cb0[11].y
  25: mul r0.y, r0.y, r0.z
  26: exp r0.y, r0.y
  27: min r0.y, r0.y, l(1.000000)
  28: mad_sat r0.y, r0.y, l(7.000000), l(-2.000000)
  29: add r0.z, -v2.y, l(1.000000)
  30: log r0.z, r0.z
  31: mul r0.z, r0.z, l(40.000000)
  32: exp r0.z, r0.z
  33: add r0.z, -r0.z, l(1.000000)
  34: max r0.z, r0.z, l(0.000000)
  35: mul r0.y, r0.z, r0.y
  36: mul r0.y, r0.y, cb0[10].w
  37: mul r0.x, r0.x, r0.y
  38: mul r0.x, r0.x, cb0[11].w
  39: mad r0.yw, v2.xxxy, cb0[12].xxxy, cb0[12].zzzw
  40: sample r3.xyzw, r0.ywyy, t4.xyzw, s4
  41: mul o0.w, r0.x, r3.w
  42: mad r0.xy, v2.xyxx, cb0[3].xyxx, cb0[3].zwzz
  43: mad r0.xy, cb1[0].yyyy, cb0[5].xyxx, r0.xyxx
  44: mad r0.xy, -r2.xyxx, cb0[6].zzzz, r0.xyxx
  45: sample r2.xyzw, r0.xyxx, t3.xyzw, s1
  46: mul r0.xyw, r1.xyxz, r2.xyxz
  47: mul r0.xyw, r0.xyxw, cb0[10].xyxz
  48: mul r0.xyw, r0.xyxw, v1.xyxz
  49: mul r0.xyz, r0.zzzz, r0.xywx
  50: mul o0.xyz, r0.xyzx, cb0[11].xxxx
  51: ret 
// Approximately 0 instruction slots used


//////////////////////////////////////////////////////
Keywords: FOG_EXP2 SOFTPARTICLES_ON
-- Hardware tier variant: Tier 1
-- Vertex shader for "d3d11":
// Stats: 24 math, 2 temp registers
Uses vertex data channel "Vertex"
Uses vertex data channel "Color"
Uses vertex data channel "TexCoord0"

Constant Buffer "UnityPerCamera" (144 bytes) on slot 0 {
  Vector4 _ProjectionParams at 80
}
Constant Buffer "UnityPerDraw" (176 bytes) on slot 1 {
  Matrix4x4 unity_ObjectToWorld at 0
}
Constant Buffer "UnityPerFrame" (368 bytes) on slot 2 {
  Matrix4x4 unity_MatrixV at 144
  Matrix4x4 unity_MatrixVP at 272
}
Constant Buffer "UnityFog" (32 bytes) on slot 3 {
  Vector4 unity_FogParams at 16
}

Shader Disassembly:
//
// Generated by Microsoft (R) D3D Shader Disassembler
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// POSITION                 0   xyzw        0     NONE   float   xyz 
// COLOR                    0   xyzw        1     NONE   float   xyzw
// TEXCOORD                 0   xyzw        2     NONE   float   xyzw
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_POSITION              0   xyzw        0      POS   float   xyzw
// COLOR                    0   xyzw        1     NONE   float   xyzw
// TEXCOORD                 0   xyzw        2     NONE   float   xyzw
// TEXCOORD                 1   x           3     NONE   float   x   
// TEXCOORD                 2   xyzw        4     NONE   float   xyzw
//
      vs_4_0
      dcl_constantbuffer CB0[6], immediateIndexed
      dcl_constantbuffer CB1[4], immediateIndexed
      dcl_constantbuffer CB2[21], immediateIndexed
      dcl_constantbuffer CB3[2], immediateIndexed
      dcl_input v0.xyz
      dcl_input v1.xyzw
      dcl_input v2.xyzw
      dcl_output_siv o0.xyzw, position
      dcl_output o1.xyzw
      dcl_output o2.xyzw
      dcl_output o3.x
      dcl_output o4.xyzw
      dcl_temps 2
   0: mul r0.xyzw, v0.yyyy, cb1[1].xyzw
   1: mad r0.xyzw, cb1[0].xyzw, v0.xxxx, r0.xyzw
   2: mad r0.xyzw, cb1[2].xyzw, v0.zzzz, r0.xyzw
   3: add r0.xyzw, r0.xyzw, cb1[3].xyzw
   4: mul r1.xyzw, r0.yyyy, cb2[18].xyzw
   5: mad r1.xyzw, cb2[17].xyzw, r0.xxxx, r1.xyzw
   6: mad r1.xyzw, cb2[19].xyzw, r0.zzzz, r1.xyzw
   7: mad r1.xyzw, cb2[20].xyzw, r0.wwww, r1.xyzw
   8: mov o0.xyzw, r1.xyzw
   9: mov o1.xyzw, v1.xyzw
  10: mov o2.xyzw, v2.xyzw
  11: div r1.z, r1.z, cb0[5].y
  12: add r1.z, -r1.z, l(1.000000)
  13: mul r1.z, r1.z, cb0[5].z
  14: max r1.z, r1.z, l(0.000000)
  15: mul r1.z, r1.z, cb3[1].x
  16: mul r1.z, r1.z, -r1.z
  17: exp o3.x, r1.z
  18: mul r0.y, r0.y, cb2[10].z
  19: mad r0.x, cb2[9].z, r0.x, r0.y
  20: mad r0.x, cb2[11].z, r0.z, r0.x
  21: mad r0.x, cb2[12].z, r0.w, r0.x
  22: mov o4.z, -r0.x
  23: mul r0.x, r1.y, cb0[5].x
  24: mul r0.w, r0.x, l(0.500000)
  25: mul r0.xz, r1.xxwx, l(0.500000, 0.000000, 0.500000, 0.000000)
  26: mov o4.w, r1.w
  27: add o4.xy, r0.zzzz, r0.xwxx
  28: ret 
// Approximately 0 instruction slots used


-- Hardware tier variant: Tier 1
-- Fragment shader for "d3d11":
// Stats: 46 math, 4 temp registers, 5 textures
Set 2D Texture "_CameraDepthTexture" to slot 0
Set 2D Texture "_Flow" to slot 1 sampler slot 2
Set 2D Texture "_Noise" to slot 2 sampler slot 3
Set 2D Texture "_MainTex" to slot 3 sampler slot 1
Set 2D Texture "_Mask" to slot 4

Constant Buffer "$Globals" (224 bytes) on slot 0 {
  Vector4 _MainTex_ST at 48
  Float _InvFade at 64
  Vector4 _SpeedMainTexUVNoiseZW at 80
  Vector4 _DistortionSpeedXYPowerZ at 96
  Vector4 _Flow_ST at 112
  Vector4 _Noise_ST at 128
  Float _PathSet0ifyouuseinPS at 144
  Vector4 _Color at 160
  Float _Emission at 176
  Float _Noisedistortpower at 180
  Float _UsePScustomdataW at 184
  Float _Opacity at 188
  Vector4 _Mask_ST at 192
  Float _Usedepth at 208
}
Constant Buffer "UnityPerCamera" (144 bytes) on slot 1 {
  Vector4 _Time at 0
  Vector4 _ZBufferParams at 112
}
Constant Buffer "UnityFog" (32 bytes) on slot 2 {
  Vector4 unity_FogColor at 0
}

Shader Disassembly:
//
// Generated by Microsoft (R) D3D Shader Disassembler
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_POSITION              0   xyzw        0      POS   float       
// COLOR                    0   xyzw        1     NONE   float   xyzw
// TEXCOORD                 0   xyzw        2     NONE   float   xyzw
// TEXCOORD                 1   x           3     NONE   float   x   
// TEXCOORD                 2   xyzw        4     NONE   float   xyzw
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Target                0   xyzw        0   TARGET   float   xyzw
//
      ps_4_0
      dcl_constantbuffer CB0[14], immediateIndexed
      dcl_constantbuffer CB1[8], immediateIndexed
      dcl_constantbuffer CB2[1], immediateIndexed
      dcl_sampler s0, mode_default
      dcl_sampler s1, mode_default
      dcl_sampler s2, mode_default
      dcl_sampler s3, mode_default
      dcl_sampler s4, mode_default
      dcl_resource_texture2d (float,float,float,float) t0
      dcl_resource_texture2d (float,float,float,float) t1
      dcl_resource_texture2d (float,float,float,float) t2
      dcl_resource_texture2d (float,float,float,float) t3
      dcl_resource_texture2d (float,float,float,float) t4
      dcl_input_ps linear v1.xyzw
      dcl_input_ps linear v2.xyzw
      dcl_input_ps linear v3.x
      dcl_input_ps linear v4.xyzw
      dcl_output o0.xyzw
      dcl_temps 4
   0: div r0.xy, v4.xyxx, v4.wwww
   1: sample r0.xyzw, r0.xyxx, t0.xyzw, s0
   2: mad r0.x, cb1[7].z, r0.x, cb1[7].w
   3: div r0.x, l(1.000000, 1.000000, 1.000000, 1.000000), r0.x
   4: add r0.x, r0.x, -v4.z
   5: mul_sat r0.x, r0.x, cb0[4].x
   6: add r0.x, r0.x, l(-1.000000)
   7: mad r0.x, cb0[13].x, r0.x, l(1.000000)
   8: mul r0.x, r0.x, v1.w
   9: mad r0.yz, v2.xxyx, cb0[8].xxyx, cb0[8].zzwz
  10: mad r1.xy, cb1[0].yyyy, cb0[5].zwzz, r0.yzyy
  11: add r0.y, v2.z, cb0[9].x
  12: add r0.z, -r0.y, r1.y
  13: add r0.y, -r0.y, l(1.000000)
  14: div r1.z, r0.z, r0.y
  15: mad r0.yz, v2.xxyx, cb0[7].xxyx, cb0[7].zzwz
  16: mad r0.yz, cb1[0].yyyy, cb0[6].xxyx, r0.yyzy
  17: sample r2.xyzw, r0.yzyy, t1.xyzw, s2
  18: mad r0.yz, -r2.xxyx, cb0[6].zzzz, r1.xxzx
  19: sample r1.xyzw, r0.yzyy, t2.xyzw, s3
  20: add_sat r1.xyzw, r1.xyzw, l(-0.100000, -0.100000, -0.100000, -0.100000)
  21: log r0.y, r1.w
  22: mov_sat r0.z, v2.w
  23: mul r0.z, r0.z, cb0[11].z
  24: mad r0.z, r0.z, l(10.000000), cb0[11].y
  25: mul r0.y, r0.y, r0.z
  26: exp r0.y, r0.y
  27: min r0.y, r0.y, l(1.000000)
  28: mad_sat r0.y, r0.y, l(7.000000), l(-2.000000)
  29: add r0.z, -v2.y, l(1.000000)
  30: log r0.z, r0.z
  31: mul r0.z, r0.z, l(40.000000)
  32: exp r0.z, r0.z
  33: add r0.z, -r0.z, l(1.000000)
  34: max r0.z, r0.z, l(0.000000)
  35: mul r0.y, r0.z, r0.y
  36: mul r0.y, r0.y, cb0[10].w
  37: mul r0.x, r0.x, r0.y
  38: mul r0.x, r0.x, cb0[11].w
  39: mad r0.yw, v2.xxxy, cb0[12].xxxy, cb0[12].zzzw
  40: sample r3.xyzw, r0.ywyy, t4.xyzw, s4
  41: mul o0.w, r0.x, r3.w
  42: mad r0.xy, v2.xyxx, cb0[3].xyxx, cb0[3].zwzz
  43: mad r0.xy, cb1[0].yyyy, cb0[5].xyxx, r0.xyxx
  44: mad r0.xy, -r2.xyxx, cb0[6].zzzz, r0.xyxx
  45: sample r2.xyzw, r0.xyxx, t3.xyzw, s1
  46: mul r0.xyw, r1.xyxz, r2.xyxz
  47: mul r0.xyw, r0.xyxw, cb0[10].xyxz
  48: mul r0.xyw, r0.xyxw, v1.xyxz
  49: mul r0.xyz, r0.zzzz, r0.xywx
  50: mad r0.xyz, r0.xyzx, cb0[11].xxxx, -cb2[0].xyzx
  51: mov_sat r0.w, v3.x
  52: mad o0.xyz, r0.wwww, r0.xyzx, cb2[0].xyzx
  53: ret 
// Approximately 0 instruction slots used


 }
}
}